### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by ghost** [siascone/makeables#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

**Comment by ghost** [comment]
Placeholder text could have margin left added to it. the buttons shouldnt have a black border around them. Makeables text could be a little bigger, also includes the projects button next to it.

**Comment by siascone** [comment]
Is there a way to hide the redux-logger from production without removing it from the package.json file before pushing to heroku everytime?

How many user seeds are necessary to be considered adequate and appropriate? I have 6 users at the moment named: Alice, Spencer, Nemo, Demo, Alec, Marshall.

researching the reroute....

Do these have to be complete before I move on to projects?

**Comment by siascone** [comment]
fixed the logger issue.

**Comment by ghost** [comment]
so what I mentioned in the comments should be very quick fixes so once you're done with that then you should go ahead and move on. The 404 page should also be made.

**Comment by ghost** [comment]
the user seeds should be around 10-15

**Comment by siascone** [comment]
User seeds updated to 15

**Comment by siascone** [comment]
Fixed invalid url reroute. Pushed to heroku for your review. I believe that covers the remaining user Auth issues.

**Comment by ghost** [comment]
place holder text is still too close to the left side

**Comment by siascone** [comment]
Okie dokie, I've adjusted the place holder spacing along with adding a house icon for the home button. The buttons have had the borders removed. Fixed some text sizing issues (better but will need refactoring once more features get added). Ready for review.

**Comment by ghost** [comment]
you're good to go!
